/**
 * Enhanced Country Seeds
 * 
 * Comprehensive country data with enterprise features including
 * currency information, geographic data, and metadata.
 */

exports.seed = async function(knex) {
  // Delete existing entries
  await knex('countries').del()
  
  // Insert enhanced country data
  await knex('countries').insert([
    {
      id: 1,
      iso: 'US',
      name: 'United States',
      nicename: 'United States',
      iso3: 'USA',
      numcode: 840,
      phonecode: 1,
      currencyCode: 'USD',
      currencyName: 'US Dollar',
      currencySymbol: '$',
      timezone: 'America/New_York',
      continent: 'North America',
      region: 'Northern America',
      capital: 'Washington, D.C.',
      latitude: 39.8283,
      longitude: -98.5795,
      population: 331900000,
      area: 9833517,
      languages: JSON.stringify(['en']),
      isActive: true,
      metadata: JSON.stringify({
        governmentType: 'Federal Republic',
        internetTLD: '.us',
        callingCode: '+1',
        drivingSide: 'right'
      })
    },
    {
      id: 2,
      iso: 'GB',
      name: 'United Kingdom',
      nicename: 'United Kingdom',
      iso3: 'GBR',
      numcode: 826,
      phonecode: 44,
      currencyCode: 'GBP',
      currencyName: 'British Pound',
      currencySymbol: '£',
      timezone: 'Europe/London',
      continent: 'Europe',
      region: 'Northern Europe',
      capital: 'London',
      latitude: 55.3781,
      longitude: -3.4360,
      population: 67800000,
      area: 243610,
      languages: JSON.stringify(['en']),
      isActive: true,
      metadata: JSON.stringify({
        governmentType: 'Constitutional Monarchy',
        internetTLD: '.uk',
        callingCode: '+44',
        drivingSide: 'left'
      })
    },
    {
      id: 3,
      iso: 'FR',
      name: 'France',
      nicename: 'France',
      iso3: 'FRA',
      numcode: 250,
      phonecode: 33,
      currencyCode: 'EUR',
      currencyName: 'Euro',
      currencySymbol: '€',
      timezone: 'Europe/Paris',
      continent: 'Europe',
      region: 'Western Europe',
      capital: 'Paris',
      latitude: 46.2276,
      longitude: 2.2137,
      population: 67390000,
      area: 643801,
      languages: JSON.stringify(['fr']),
      isActive: true,
      metadata: JSON.stringify({
        governmentType: 'Republic',
        internetTLD: '.fr',
        callingCode: '+33',
        drivingSide: 'right'
      })
    },
    {
      id: 4,
      iso: 'DE',
      name: 'Germany',
      nicename: 'Germany',
      iso3: 'DEU',
      numcode: 276,
      phonecode: 49,
      currencyCode: 'EUR',
      currencyName: 'Euro',
      currencySymbol: '€',
      timezone: 'Europe/Berlin',
      continent: 'Europe',
      region: 'Western Europe',
      capital: 'Berlin',
      latitude: 51.1657,
      longitude: 10.4515,
      population: 83200000,
      area: 357114,
      languages: JSON.stringify(['de']),
      isActive: true,
      metadata: JSON.stringify({
        governmentType: 'Federal Republic',
        internetTLD: '.de',
        callingCode: '+49',
        drivingSide: 'right'
      })
    },
    {
      id: 5,
      iso: 'JP',
      name: 'Japan',
      nicename: 'Japan',
      iso3: 'JPN',
      numcode: 392,
      phonecode: 81,
      currencyCode: 'JPY',
      currencyName: 'Japanese Yen',
      currencySymbol: '¥',
      timezone: 'Asia/Tokyo',
      continent: 'Asia',
      region: 'Eastern Asia',
      capital: 'Tokyo',
      latitude: 36.2048,
      longitude: 138.2529,
      population: 125800000,
      area: 377930,
      languages: JSON.stringify(['ja']),
      isActive: true,
      metadata: JSON.stringify({
        governmentType: 'Constitutional Monarchy',
        internetTLD: '.jp',
        callingCode: '+81',
        drivingSide: 'left'
      })
    },
    {
      id: 6,
      iso: 'CN',
      name: 'China',
      nicename: 'China',
      iso3: 'CHN',
      numcode: 156,
      phonecode: 86,
      currencyCode: 'CNY',
      currencyName: 'Chinese Yuan',
      currencySymbol: '¥',
      timezone: 'Asia/Shanghai',
      continent: 'Asia',
      region: 'Eastern Asia',
      capital: 'Beijing',
      latitude: 35.8617,
      longitude: 104.1954,
      population: 1439000000,
      area: 9596960,
      languages: JSON.stringify(['zh']),
      isActive: true,
      metadata: JSON.stringify({
        governmentType: 'Socialist Republic',
        internetTLD: '.cn',
        callingCode: '+86',
        drivingSide: 'right'
      })
    },
    {
      id: 7,
      iso: 'IN',
      name: 'India',
      nicename: 'India',
      iso3: 'IND',
      numcode: 356,
      phonecode: 91,
      currencyCode: 'INR',
      currencyName: 'Indian Rupee',
      currencySymbol: '₹',
      timezone: 'Asia/Kolkata',
      continent: 'Asia',
      region: 'Southern Asia',
      capital: 'New Delhi',
      latitude: 20.5937,
      longitude: 78.9629,
      population: 1380000000,
      area: 3287263,
      languages: JSON.stringify(['hi', 'en']),
      isActive: true,
      metadata: JSON.stringify({
        governmentType: 'Federal Republic',
        internetTLD: '.in',
        callingCode: '+91',
        drivingSide: 'left'
      })
    },
    {
      id: 8,
      iso: 'CA',
      name: 'Canada',
      nicename: 'Canada',
      iso3: 'CAN',
      numcode: 124,
      phonecode: 1,
      currencyCode: 'CAD',
      currencyName: 'Canadian Dollar',
      currencySymbol: 'C$',
      timezone: 'America/Toronto',
      continent: 'North America',
      region: 'Northern America',
      capital: 'Ottawa',
      latitude: 56.1304,
      longitude: -106.3468,
      population: 38000000,
      area: 9984670,
      languages: JSON.stringify(['en', 'fr']),
      isActive: true,
      metadata: JSON.stringify({
        governmentType: 'Federal Parliamentary Democracy',
        internetTLD: '.ca',
        callingCode: '+1',
        drivingSide: 'right'
      })
    },
    {
      id: 9,
      iso: 'AU',
      name: 'Australia',
      nicename: 'Australia',
      iso3: 'AUS',
      numcode: 36,
      phonecode: 61,
      currencyCode: 'AUD',
      currencyName: 'Australian Dollar',
      currencySymbol: 'A$',
      timezone: 'Australia/Sydney',
      continent: 'Oceania',
      region: 'Australia and New Zealand',
      capital: 'Canberra',
      latitude: -25.2744,
      longitude: 133.7751,
      population: 25700000,
      area: 7692024,
      languages: JSON.stringify(['en']),
      isActive: true,
      metadata: JSON.stringify({
        governmentType: 'Federal Parliamentary Democracy',
        internetTLD: '.au',
        callingCode: '+61',
        drivingSide: 'left'
      })
    },
    {
      id: 10,
      iso: 'BR',
      name: 'Brazil',
      nicename: 'Brazil',
      iso3: 'BRA',
      numcode: 76,
      phonecode: 55,
      currencyCode: 'BRL',
      currencyName: 'Brazilian Real',
      currencySymbol: 'R$',
      timezone: 'America/Sao_Paulo',
      continent: 'South America',
      region: 'South America',
      capital: 'Brasília',
      latitude: -14.2350,
      longitude: -51.9253,
      population: 213000000,
      area: 8514877,
      languages: JSON.stringify(['pt']),
      isActive: true,
      metadata: JSON.stringify({
        governmentType: 'Federal Republic',
        internetTLD: '.br',
        callingCode: '+55',
        drivingSide: 'right'
      })
    }
  ])
}