language: node_js
sudo: false
node_js:
  - node
cache:
   directories:
     — “node_modules”
notifications:
  slack: moayyadz:Hs9XPwBHrG2119SXM7T205Al

env:
  -  NODE_ENV=test
  
services:
  - postgresql

before_script:
  - cp .env.example .env
  - psql -c 'create database susanoo;' -U postgres
  - psql -c "CREATE USER root WITH PASSWORD 'Admin@123';" -U postgres
  - export DB_USER=root
  - export DB_PASSWORD=Admin@123

script: npm run test-script