language: node_js
sudo: false
node_js:
  - node
cache:
   directories:
     — “node_modules”
notifications:
  slack: moayyadz:Hs9XPwBHrG2119SXM7T205Al

env:
  - DB_USER=root
  - DB_PASSWORD=Admin@123
  - SMTP_USERNAME=TEST_USER
  - SMTP_PASSWORD=TEST_PASSWORD
  - SMTP_HOST=TEST_HOST
  - TWILIO_AUTH_TOKEN=123456789012345678901234567890
  - TWILIO_ACCOUNT_SID=AC123456789012345678901234567890
  - PHONE_FROM=12345678
  - IP_LOOKUP_ACCESS_TOKEN=AB123456789012345678901234567890

services:
  - postgresql

before_script:
  - cp .env.example .env
  - psql -c 'create database susanoo;' -U postgres
  - psql -c "CREATE USER root WITH PASSWORD 'Admin@123';" -U postgres

script: npm run test-script